#!/usr/bin/env python3
"""
MCP-Claude-mem-local Context Hook
Injects memory context into CLAUDE.md files.
"""

import asyncio
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

import asyncpg
from dotenv import load_dotenv

# Load configuration
env_path = Path(__file__).parent.parent.parent / ".env"
load_dotenv(env_path)

PG_HOST = os.getenv("PG_HOST", "localhost")
PG_PORT = int(os.getenv("PG_PORT", "5432"))
PG_DATABASE = os.getenv("PG_DATABASE", "claude_memory")
PG_USER = os.getenv("PG_USER", "claude")
PG_PASSWORD = os.getenv("PG_PASSWORD")
if not PG_PASSWORD:
    print(json.dumps({"error": "PG_PASSWORD environment variable is required"}))
    sys.exit(1)

# Category icons
TYPE_ICONS = {
    "bugfix": "🔴",
    "decision": "🟠",
    "feature": "🟢",
    "discovery": "🔵",
    "refactor": "🟣",
    "change": "⚪",
    "learning": "🟡",
    "pattern": "🟤",
    "error_solution": "🔴"
}


async def get_memories_for_project(project_path: str) -> list:
    """Retrieve memories associated with a project/directory."""
    try:
        conn = await asyncpg.connect(
            host=PG_HOST,
            port=PG_PORT,
            database=PG_DATABASE,
            user=PG_USER,
            password=PG_PASSWORD
        )
        
        project_name = os.path.basename(project_path)
        
        memories = await conn.fetch("""
            SELECT 
                id, summary, category, created_at, importance_score,
                LENGTH(content) as content_length
            FROM memories
            WHERE project_context ILIKE $1
               OR project_context ILIKE $2
            ORDER BY created_at DESC
            LIMIT 30
        """, f"%{project_name}%", f"%{project_path}%")
        
        await conn.close()
        return memories
        
    except Exception as e:
        print(json.dumps({"error": str(e), "type": "connection"}))
        return []


def generate_context_block(memories: list) -> str:
    """Generate markdown context block."""
    if not memories:
        return ""
    
    # Group by date
    by_date = {}
    for mem in memories:
        if mem["created_at"]:
            date_key = mem["created_at"].strftime("%b %d, %Y")
        else:
            date_key = "Unknown"
        if date_key not in by_date:
            by_date[date_key] = []
        by_date[date_key].append(mem)
    
    lines = [
        "<mcp-claude-mem-local-context>",
        "# Recent Activity",
        "",
        "<!-- This section is auto-generated by MCP-Claude-mem-local. Edit content outside the tags. -->",
        ""
    ]
    
    for date, mems in by_date.items():
        lines.append(f"### {date}")
        lines.append("")
        lines.append("| ID | Time | T | Title | Read |")
        lines.append("|----|------|---|-------|------|")
        
        for mem in mems:
            time_str = mem["created_at"].strftime("%I:%M %p") if mem["created_at"] else ""
            icon = TYPE_ICONS.get(mem["category"], "⚪")
            summary = (mem["summary"] or "")[:50].replace("|", "-").replace("\n", " ")
            tokens = f"~{mem['content_length'] // 4}" if mem["content_length"] else "?"
            mem_id = str(mem["id"])[:8]
            
            lines.append(f"| #{mem_id} | {time_str} | {icon} | {summary} | {tokens} |")
        
        lines.append("")
    
    lines.append("</mcp-claude-mem-local-context>")
    return "\n".join(lines)


def sanitize_path(directory: str) -> str | None:
    """
    Validate and sanitize directory path to prevent path traversal attacks.
    Returns None if path is invalid or outside allowed locations.
    """
    try:
        # Resolve to absolute path
        resolved = Path(directory).resolve()

        # Check for path traversal attempts
        if ".." in str(resolved):
            return None

        # Must be a directory
        if not resolved.is_dir():
            return None

        # Only allow paths within user's home directory or typical project locations
        home = Path.home()
        allowed_roots = [
            home,
            Path("/tmp"),
            Path("/var/folders"),  # macOS temp
        ]

        if not any(str(resolved).startswith(str(root)) for root in allowed_roots):
            return None

        return str(resolved)
    except Exception:
        return None


def inject_into_claude_md(directory: str, context_block: str) -> bool:
    """Inject or update context in CLAUDE.md."""
    # Security: Validate directory path
    safe_directory = sanitize_path(directory)
    if not safe_directory:
        print(json.dumps({"error": f"Invalid or unsafe directory path", "type": "security"}))
        return False

    claude_md_path = os.path.join(safe_directory, "CLAUDE.md")
    pattern = r"<mcp-claude-mem-local-context>.*?</mcp-claude-mem-local-context>"

    try:
        if os.path.exists(claude_md_path):
            with open(claude_md_path, "r", encoding="utf-8") as f:
                content = f.read()

            if re.search(pattern, content, re.DOTALL):
                # Security: Use a lambda to avoid regex special chars in replacement
                new_content = re.sub(
                    pattern,
                    lambda m: context_block,  # Safe replacement
                    content,
                    flags=re.DOTALL
                )
            else:
                # Append to end
                new_content = content.rstrip() + "\n\n" + context_block + "\n"
        else:
            # Create new file
            new_content = f"# CLAUDE.md\n\nProject configuration for Claude Code.\n\n{context_block}\n"

        with open(claude_md_path, "w", encoding="utf-8") as f:
            f.write(new_content)

        return True

    except Exception as e:
        # Security: Don't expose full exception details
        print(json.dumps({"error": "Failed to write CLAUDE.md", "type": "write"}))
        return False


async def process_directory(directory: str) -> dict:
    """Process a directory and inject context."""
    memories = await get_memories_for_project(directory)
    
    result = {
        "directory": directory,
        "memories_count": len(memories),
        "status": "no_memories"
    }
    
    if memories:
        context_block = generate_context_block(memories)
        if inject_into_claude_md(directory, context_block):
            result["status"] = "updated"
        else:
            result["status"] = "error"
    
    return result


async def main():
    """Main entry point."""
    action = sys.argv[1] if len(sys.argv) > 1 else "session-start"
    
    # Get current directory (passed by Claude Code or cwd)
    cwd = os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())
    
    if action in ("session-start", "post-tool", "stop"):
        result = await process_directory(cwd)
        print(json.dumps(result))
    else:
        print(json.dumps({"error": f"Unknown action: {action}", "type": "usage"}))
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())