# AUTO-GENERATED by manage_env.py — ne pas modifier manuellement.
# Ce fichier est réécrit à chaque déploiement.
terraform {
  backend "gcs" {
    bucket = "z-gcp-summit-tf-state"
    prefix = "terraform/state/prd/mcp-claude-memory"
  }
}
